services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - db
        env_file:
            - .env
        environment:
            - DB_HOST=db # This overrides the value from .env

    db:
        image: postgres:16.4
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres_data: # This line defines the volume
